# Generated by Django 2.2 on 2021-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('pub_date', models.DateField(default='2021-01-19')),
                ('due_date', models.DateField(default='2021-01-19')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
